mongodb:
  image: mongo:latest
  container_name: MongoDB
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
  ports:
    - 27017:27017
  volumes:
    - ./data/db:/data/db