mongodb:
  image: bitnami/mongodb:latest
  container_name: MongoDB
  environment:
    - MONGODB_USERNAME=myapp
    - MONGODB_PASSWORD=myapp
    - MONGODB_DATABASE=e-commerce
  ports:
    - 27017:27017
  volumes:
    - ./data/db:/data/db